#!/bin/bash
#
# pibrick-tools — system-wide dispatcher for the piBrick driver installer.
#
# Installed by install.sh into /usr/local/bin so users can run
#   sudo pibrick-tools --battery-status
#   sudo pibrick-tools --apply-calibration
#   sudo pibrick-tools --install battery-new
# without having to remember the install.sh path under /usr/lib/pibrick/.
#
# This is a thin wrapper: every argument is forwarded to
# /usr/lib/pibrick/install.sh. We refuse to run as a non-root user
# unless the wrapped command is read-only (status, help, --version).
#
# The wrapper is generated by install.sh. If you want to customize
# the install location, edit install.sh and re-run it.

set -euo pipefail

INSTALL_SH="/usr/lib/pibrick/install.sh"

if [ ! -f "$INSTALL_SH" ]; then
	echo "pibrick-tools: $INSTALL_SH not found." >&2
	echo "  Run \`sudo bash ./install.sh\` from the pibrick-driver repo first," >&2
	echo "  or reinstall via your package manager." >&2
	exit 1
fi

# Read-only subcommands that do not require root. Anything else
# (--install, --apply-calibration, --enable-calibration, --battery-config)
# does need root because it touches /etc/modprobe.d/, /sys, or the kernel.
needs_root() {
	local arg
	for arg in "$@"; do
		case "$arg" in
			--status-calibration|--battery-status|--version|-h|--help|help)
				return 1 ;;
		esac
	done
	return 0
}

if needs_root "$@"; then
	if [ "$(id -u)" != "0" ]; then
		echo "pibrick-tools: this command modifies the system; please re-run with sudo:" >&2
		echo "  sudo pibrick-tools $*" >&2
		exit 1
	fi
fi

exec "$INSTALL_SH" "$@"
